name = "gigahd/smapshot"
version = "0.2.0"
description = "A small library for saving and loading maps"
authors = ["gigahd"]
license = "MIT"
repository = "https://github.com/gigahd/Smapshot"
includes = ["src/**", "README.md", "pesde.toml"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"