[package]
name = "gigahd/smapshot"
description = "A small library for saving and loading maps"
version = "0.1.1"
license = "MIT"
authors = ["gigahd"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/gigahd/Smapshot"

exclude = ["*"]
include = [
    "wally.toml",
    "README.md",
    "LICENSE",
    "default.project.json",
    "src",
    "src/**"
]