-- See https://create.roblox.com/docs/studio/properties#instance-attributes for more infos
local validTypesList = {
    string = true,
    number = true,
    boolean = true,
    UDim = true,
    UDim2 = true,
    BrickColor = true,
    Color3 = true,
    Vector2 = true,
    Vector3 = true,
    CFrame = true,
    NumberSequence = true,
    ColorSequence = true,
    NumberRange = true,
    Rect = true,
    Font = true,
}

return validTypesList